apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "java-app.name" . }}
    helm.sh/chart: {{ include "java-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "java-app.name" . }}
  ports:
    - port: 80           # Port the service listens on
      targetPort: 8080    # Port your app listens on internally
      nodePort: 30080     # Expose the service on NodePort 30080
      protocol: TCP
  type: NodePort         # Changed from LoadBalancer to NodePort
