replicaCount: 1

image:
  repository:  ghcr.io/suppada/springboot/java-chart
  pullPolicy: IfNotPresent
  tag: "0.1.0"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080 

ingress:
  enabled: true
  hosts:
    - host: app.k8s-dev.rocks
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
