name: Helm Chart Deployment
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
        default: "ghcr.io"
      chart_name:
        description: 'Name of the Helm Chart'
        required: true
        type: string
      chart_version:
        description: 'Version of the Helm Chart'
        required: true
        type: string

jobs:
  helm_package_and_push:
    name: Package and Push Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Log in to GitHub Container Registry (for Helm)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ inputs.registry }} -u ${{ github.actor }} --password-stdin
      - name: Package Helm Chart
        run: |
          helm package ${{ inputs.chart_name }} --version ${{ inputs.chart_version }}
      - name: Push Helm Chart to OCI Registry
        run: |
          helm push ${{ inputs.chart_name }}-${{ inputs.chart_version }}.tgz oci://${{ inputs.registry }}/${{ github.repository }}/java-chart
      - name: Logout from Helm Registry
        run: helm registry logout ${{ inputs.registry }}