name: Maven Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  maven_build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Maven Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact
          path: target/*.war