name: Maven Build
on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      enable_release:
        required: false
        type: boolean
        default: false

jobs:
  maven_build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Artifact to GitHub Release
        if: ${{ inputs.enable_release }}
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.war
          tag_name: latest-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}